services:
  mongo-db:
    image: mongo:5.0
    container_name: mongo-db
    networks:
      - fiware_default
    expose:
      - "27017"
    volumes:
      - mongo-db:/data/db
    command: --bind_ip_all

  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - .config/postgres/init:/docker-entrypoint-initdb.d
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    hostname: backend
    networks:
      - fiware_default
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./backend:/app
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]

  orion-ld:
    image: fiware/orion-ld
    container_name: fiware-orionld
    hostname: orion
    networks:
      - fiware_default
    ports:
      - "1026:1026"
    command: -dbhost mongo-db
    depends_on:
      - mongo-db
    healthcheck:
      test: wget --spider -q http://fiware-orion:1026/version || exit 1

  ld-context:
    image: httpd:alpine
    hostname: context
    container_name: fiware-ld-context
    networks:
      - fiware_default
    ports:
      - "3004:80"
    volumes:
      - ./ld-context-files:/usr/local/apache2/htdocs/

networks:
  fiware_default:
    driver: bridge

volumes:
  mongo-db:
  postgres-db:
